<a href="https://colab.research.google.com/github/Sneha2025L/SnehaGoogleColabFiles/blob/main/Copy_of_Getting_started_with_google_colab_ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("tysonpo/ice-cream-dataset")

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/tysonpo/ice-cream-dataset?dataset_version_number=3...

100%|██████████| 52.8M/52.8M [00:00<00:00, 101MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/tysonpo/ice-cream-dataset/versions/3

In [2]:
import pandas as pd

combined_df = pd.read_csv('/kaggle/input/ice-cream-dataset/combined/combined.csv')
display(combined_df.head())

FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/input/ice-cream-dataset/combined/combined.csv'

In [ ]:
import pandas as pd

products_df = pd.read_csv('/kaggle/input/ice-cream-dataset/combined/products.csv')
display(products_df.head())

In [ ]:
!ls /kaggle/input/ice-cream-dataset/combined

In [ ]:
!ls /kaggle/input/ice-cream-dataset

Colab is making it easier than ever to integrate powerful Generative AI capabilities into your projects. We are launching public preview for a simple and intuitive Python library (google.colab.ai) to access state-of-the-art language models directly within Colab environments. All users have free access to most popular LLMs, while paid users have access to a wider selection of models. This means users can spend less time on configuration and set up and more time bringing their ideas to life. With just a few lines of code, you can now perform a variety of tasks:
- Generate text
- Translate languages
- Write creative content
- Categorize text

Happy Coding!


[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/googlecolab/colabtools/blob/main/notebooks/Getting_started_with_google_colab_ai.ipynb)

In [ ]:
# @title List available models
from google.colab import ai

ai.list_models()

Choosing a Model
The model names give you a hint about their capabilities and intended use:

Pro: These are the most capable models, ideal for complex reasoning, creative tasks, and detailed analysis.

Flash: These models are optimized for high speed and efficiency, making them great for summarization, chat applications, and tasks requiring rapid responses.

Gemma: These are lightweight, open-weight models suitable for a variety of text generation tasks and are great for experimentation.

In [ ]:
# @title Simple batch generation example
# Only text-to-text input/output is supported
from google.colab import ai

response = ai.generate_text("What is the capital of France?")
print(response)

In [ ]:
# @title Choose a different model
from google.colab import ai

response = ai.generate_text("What is the capital of England", model_name='google/gemini-2.0-flash-lite')
print(response)

For longer text generations, you can stream the response. This displays the output token by token as it's generated, rather than waiting for the entire response to complete. This provides a more interactive and responsive experience. To enable this, simply set stream=True.

In [ ]:
# @title Simple streaming example
from google.colab import ai

stream = ai.generate_text("Tell me a short story.", stream=True)
for text in stream:
  print(text, end='')

In [ ]:
#@title Text formatting setup
#code is not necessary for colab.ai, but is useful in fomatting text chunks
import sys

class LineWrapper:
    def __init__(self, max_length=80):
        self.max_length = max_length
        self.current_line_length = 0

    def print(self, text_chunk):
        i = 0
        n = len(text_chunk)
        while i < n:
            start_index = i
            while i < n and text_chunk[i] not in ' \n': # Find end of word
                i += 1
            current_word = text_chunk[start_index:i]

            delimiter = ""
            if i < n: # If not end of chunk, we found a delimiter
                delimiter = text_chunk[i]
                i += 1 # Consume delimiter

            if current_word:
                needs_leading_space = (self.current_line_length > 0)

                # Case 1: Word itself is too long for a line (must be broken)
                if len(current_word) > self.max_length:
                    if needs_leading_space: # Newline if current line has content
                        sys.stdout.write('\n')
                        self.current_line_length = 0
                    for char_val in current_word: # Break the long word
                        if self.current_line_length >= self.max_length:
                            sys.stdout.write('\n')
                            self.current_line_length = 0
                        sys.stdout.write(char_val)
                        self.current_line_length += 1
                # Case 2: Word doesn't fit on current line (print on new line)
                elif self.current_line_length + (1 if needs_leading_space else 0) + len(current_word) > self.max_length:
                    sys.stdout.write('\n')
                    sys.stdout.write(current_word)
                    self.current_line_length = len(current_word)
                # Case 3: Word fits on current line
                else:
                    if needs_leading_space:
                        # Define punctuation that should not have a leading space
                        # when they form an entire "word" (token) following another word.
                        no_leading_space_punctuation = {
                            ",", ".", ";", ":", "!", "?",        # Standard sentence punctuation
                            ")", "]", "}",                     # Closing brackets
                            "'s", "'S", "'re", "'RE", "'ve", "'VE", # Common contractions
                            "'m", "'M", "'ll", "'LL", "'d", "'D",
                            "n't", "N'T",
                            "...", "…"                          # Ellipses
                        }
                        if current_word not in no_leading_space_punctuation:
                            sys.stdout.write(' ')
                            self.current_line_length += 1
                    sys.stdout.write(current_word)
                    self.current_line_length += len(current_word)

            if delimiter == '\n':
                sys.stdout.write('\n')
                self.current_line_length = 0
            elif delimiter == ' ':
                # If line is full and a space delimiter arrives, it implies a wrap.
                if self.current_line_length >= self.max_length:
                    sys.stdout.write('\n')
                    self.current_line_length = 0

        sys.stdout.flush()

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("tysonpo/ice-cream-dataset")

print("Path to dataset files:", path)

In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

In [ ]:
    import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
  loss='sparse_categorical_crossentropy',
  metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

bold text

# ***`title`***
markdown

# Task
Load the dataset from "/kaggle/input/ice-cream-dataset/combined.csv" and display the first 5 rows.

## Verify the dataset path

### Subtask:
Double-check the exact path where the dataset was downloaded.

## List files at the verified path

### Subtask:
Use a shell command to list the files in the directory identified in the previous step to confirm the presence and exact name of the `combined.csv` file.

**Reasoning**:
Use the `!ls` shell command to list the files in the directory where the dataset was downloaded.

In [ ]:
!ls /root/.cache/kagglehub/datasets/tysonpo/ice-cream-dataset/versions/3

**Reasoning**:
The previous step confirmed that the `combined` directory exists within the downloaded dataset. Now, list the contents of the `combined` directory to find the `combined.csv` file.

In [ ]:
!ls /root/.cache/kagglehub/datasets/tysonpo/ice-cream-dataset/versions/3/combined

## Load the data

### Subtask:
Use the verified path and filename to load the `combined.csv` file into a pandas DataFrame.

**Reasoning**:
The previous step confirmed that `combined.csv` does not exist, but `products.csv` does exist in the `combined` directory. Based on the instructions, I will load `products.csv` as `combined_df`.

In [ ]:
import pandas as pd

combined_df = pd.read_csv('/root/.cache/kagglehub/datasets/tysonpo/ice-cream-dataset/versions/3/combined/products.csv')

**Reasoning**:
The instructions state to load the `products.csv` file into a DataFrame and display the first 5 rows. I have loaded the DataFrame in the previous step, and now I will display the first 5 rows as requested in the original task description.

In [ ]:
display(combined_df.head())

## Display the head

### Subtask:
Display the first 5 rows of the DataFrame.

**Reasoning**:
Display the first 5 rows of the DataFrame as requested by the subtask.

In [ ]:
display(combined_df.head())

## Summary:

### Data Analysis Key Findings

* The `combined.csv` file was not found at the specified path.
* The `products.csv` file was successfully loaded into a pandas DataFrame instead of `combined.csv`.
* The first 5 rows of the loaded `products.csv` DataFrame were displayed, showing columns including 'brand', 'key', 'name', 'subhead', 'description', 'rating', 'rating\_count', and 'ingredients'.

### Insights or Next Steps

* Investigate if `products.csv` contains the necessary data for the analysis, as `combined.csv` was not available.
* Update subsequent steps to use the `combined_df` DataFrame loaded with `products.csv`.

# Task
Analyze the "products.csv" dataset to predict ice cream ratings.

## Load the dataset

### Subtask:
Load the `products.csv` file into a pandas DataFrame.

**Reasoning**:
Load the `products.csv` file into a pandas DataFrame as requested by the subtask.

In [3]:
products_df = pd.read_csv('/root/.cache/kagglehub/datasets/tysonpo/ice-cream-dataset/versions/3/combined/products.csv')

## Explore and preprocess the data

### Subtask:
Analyze the data types, check for missing values, and perform necessary data cleaning and transformations. This may include handling categorical variables, scaling numerical features, and addressing any inconsistencies.

**Reasoning**:
Display the data types, check for missing values, display descriptive statistics for numerical columns, and display unique values and their counts for categorical columns to understand the dataset's structure and identify areas for cleaning and transformation.

In [4]:
display(products_df.info())
display(products_df.isnull().sum())
display(products_df.describe())
for col in products_df.select_dtypes(include='object').columns:
    display(products_df[col].value_counts())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         241 non-null    object
 1   key           241 non-null    object
 2   name          241 non-null    object
 3   subhead       57 non-null     object
 4   description   237 non-null    object
 5   rating        241 non-null    float64
 6   rating_count  241 non-null    int64
 7   ingredients   241 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 15.2+ KB

None

brand             0
key               0
name              0
subhead         184
description       4
rating            0
rating_count      0
ingredients       0
dtype: int64

           rating  rating_count
count  241.000000    241.000000
mean     4.223237     90.016598
std      0.620383    111.349449
min      1.200000      2.000000
25%      4.000000     28.000000
50%      4.400000     59.000000
75%      4.700000    112.000000
max      5.000000    983.000000

brand
hd         70
breyers    69
bj         57
talenti    45
Name: count, dtype: int64

key
0_bj          1
1_bj          1
2_bj          1
3_bj          1
4_bj          1
             ..
64_breyers    1
65_breyers    1
66_breyers    1
67_breyers    1
68_breyers    1
Name: count, Length: 241, dtype: int64

name
Chocolate Chip Cookie Dough           2
Salted Caramel Core                   1
Chip Happens                          1
Netflix & Chilll'd™                   1
Gimme S’more!™                        1
                                     ..
CINNABON®                             1
CarbSmart™ Caramel Swirl Bar          1
Layered Dessert S'mores               1
Layered Dessert Peach Cobbler         1
Layered Dessert Brownie Cheesecake    1
Name: count, Length: 240, dtype: int64

subhead
Sweet Cream Ice Cream with Blonde Brownies & a Salted Caramel Core                                                                                           1
Peanut Butter Ice Cream with Sweet & Salty Pretzel Swirls & Fudge Brownies                                                                                   1
A Cold Mess of Chocolate Ice Cream with Fudge Chips & Crunchy Potato Chip Swirls                                                                             1
Mascarpone Ice Cream with Fudge-Covered Pastry Shell Pieces & Mascarpone Swirls                                                                              1
Toasted Marshmallow Ice Cream with Chocolate Cookie Swirls, Graham Cracker Swirls & Fudge Flakes                                                             1
Chocolate & Peanut Butter Ice Creams Mixed with Gobs of Peanut Butter Cookie Dough & Fudge Brownies                                                          1
Blackberry & Mascarpone Ice Creams with Shortbread Cookies & Fudge-Covered Almonds                                                                           1
Chocolate & Banana Ice Creams with Mini Peanut Butter Cups                                                                                                   1
Cinnamon & Chocolate Ice Creams with Gobs of Cinnamon Bun Dough & Spicy Fudge Brownies                                                                       1
A Universe of Milk Chocolate Ice Cream with Fudge Cows & Toffee Meteor Clusters Orbiting a Sugar Cookie Dough Core                                           1
Vanilla Ice Cream with Fudge-Covered Waffle Cone Pieces & a Caramel Swirl                                                                                    1
Buttery Bourbon Ice Cream with Pecans, Shortbread Cookie Pieces & a Whiskey Caramel Swirl                                                                    1
Coffee Ice Cream with Fudge Chunks & a Brownie Batter Swirl                                                                                                  1
Caramel Cheesecake Ice Cream with Cheesecake Pieces & Chocolate Cookie Swirls                                                                                1
Cherry Ice Cream with Cherries & Fudge Flakes                                                                                                                1
Cold Brew Coffee Ice Cream with Chocolate Cookie-Covered Coffee Liqueur Truffles & Fudge Swirls                                                              1
Vanilla Ice Cream with Gobs of Chocolate Chip Cookie Dough                                                                                                   1
Chocolate Ice Cream with Fudge Brownies                                                                                                                      1
Chocolate Malt Milkshake Ice Cream With Salted Fudge Pieces & Marshmallow Swirls                                                                             1
Chocolate Ice Cream with Chocolate Cookies & Swirls of Chocolate Pudding Ice Cream                                                                           1
Vanilla Malt Ice Cream with Peanutty Fudge-Covered Pretzels with Fudge & Peanut Buttery Swirls                                                               1
Banana Ice Cream with Fudge Chunks & Walnuts                                                                                                                 1
Caramel Ice Cream with Cinnamon Bun Dough & a Cinnamon Streusel Swirl                                                                                        1
Coffee Ice Cream with Espresso Bean Fudge Chunks                                                                                                             1
Coffee Ice Cream with Fudge-Covered Toffee Pieces                                                                                                            1
Cold Brew & Sweet Cream Ice Creams with Salted Caramel Swirls                                                                                                1
A Collision of Chocolate & Vanilla Ice Creams mixed with Peanut Butter Cups, Fudge-Covered Toffee Pieces, White Chocolatey Chunks & Fudge-Covered Almonds    1
Chocolate Ice Cream with Crunchy Pretzel Swirls, Marshmallow Swirls & Fudge-Covered Almonds                                                                  1
Chocolate & Vanilla Ice Creams mixed with Gobs of Chocolate Chip Cookie Dough & Fudge Brownies                                                               1
Vanilla Ice Cream with Chocolate Sandwich Cookies & Chocolate Cookie Swirls                                                                                  1
Vanilla Ice Cream with a Chocolate Cookie Swirl, Chocolate Chip & Chocolate Chocolate Chip Cookies                                                           1
Peppermint Ice Cream with Chocolate Sandwich Cookies                                                                                                         1
Dark Chocolate Mint Ice Cream with Marshmallow Swirls & Chocolate Cookie Swirls                                                                              1
Chocolate Ice Cream with White & Dark Fudge Chunks, Pecans, Walnuts & Fudge-Covered Almonds                                                                  1
Buttery Brown Sugar Ice Cream with Fudge Flakes & Oatmeal Cinnamon Cookie Swirls                                                                             1
Peanut Butter Ice Cream with Peanut Butter Cups                                                                                                              1
Milk Chocolate Ice Cream with Peanut Buttery Swirls & Chocolate Cookie Swirls                                                                                1
Chocolate Ice Cream with Gooey Marshmallow Swirls, Caramel Swirls & Fudge Fish                                                                               1
Pistachio Ice Cream with Lightly Roasted Pistachios                                                                                                          1
Pumpkin Cheesecake Ice Cream with a Graham Cracker Swirl                                                                                                     1
Blueberry & Raspberry Ice Cream swirled with Vanilla Ice Cream with Strawberries & Shortbread Pieces                                                         1
Chocolate Ice Cream with Fudge Chunks, Toasted Marshmallow & Graham Cracker Swirls                                                                           1
Vanilla Bean Ice Cream with Roasted Almond Slivers, Fudge Flakes & a Salted Caramel Swirl                                                                    1
Strawberry Cheesecake Ice Cream with Strawberries & a Thick Graham Cracker Swirl                                                                             1
Caramel & Chocolate Ice Creams with Chocolate Cookie Swirls & Gobs of Chocolate Chip Cookie Dough & Peanut Butter Cookie Dough.                              1
Caramel Ice Cream with a Swirl of Caramel & Fudge-Covered Caramel Chunks                                                                                     1
Burnt Caramel Ice Cream with Almonds, Fudge Flakes & Bourbon Caramel Swirls                                                                                  1
Vanilla Ice Cream                                                                                                                                            1
Vanilla Ice Cream with Swirls of Caramel & Fudge                                                                                                             1
Mocha & Caramel Ice Creams with Chocolate Cookies, Fudge Flakes & a Chocolate Cookie Core                                                                    1
Cookie Milk Ice Cream with Fudge Chips & a Chocolate Chip Cookie Dough Core                                                                                  1
Sweet Cream Ice Cream with a hint of Almond flavor & Shortbread Cookies & Cherry Ice Cream with Cherries & a Sugar Cookie Dough Core                         1
Vanilla Ice Cream with Peanut Butter Cookies, Peanut Butter Ice Cream with Fudge Chips & a No Bake Cookie Dough Core                                         1
Chocolate & Vanilla Ice Creams with Fudge Brownies & a Brownie Batter Core                                                                                   1
Chocolate & Cheesecake Ice Creams with Chocolate Cookies & a Cheesecake Core                                                                                 1
Chocolate & Caramel Ice Creams with Fudge Chips & a Soft Caramel Core                                                                                        1
Chocolate & Peanut Butter Ice Creams with Mini Peanut Butter Cups & a Peanut Butter Fudge Core                                                               1
Name: count, dtype: int64

description
Find your way to the ultimate ice cream experience with our Cores. Whether your primal urges lead you to the center of salted caramel or directly to the blonde brownies, you’ll be in total control of your own ice cream destiny.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
There’s something for everyone to watch on Netflix & flavors for everyone to enjoy from Ben & Jerry’s, so we’ve teamed up to bring you a chillaxing new creation that’s certain to satisfy any sweet or salty snack craving. It’s a flavorful world, and everyone is invited to grab a spoon.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
Sometimes “chip” happens and everything’s a mess, but we Nailed It! with this chip-filled limited batch. When smooth chocolate ice cream meets fudge chips & salty swirls, they pack a serious one-two crunch. The best part? There won’t be anything left to clean up.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
As a Limited Batch that captured the rapture of the classic Sicilian dessert, our Cannoli captivated fans like no other Cannoli could. Now that it’s a full-time flavor, you and your Cannoli can re-capture the rapture all over again.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1
It’s a gimme: there’s always room for s’more. And we’re pretty sure you’ll want to make s’more room in your freezer for this ‘shmallowy-rich, graham-good-‘n-chocolatey concoction now that it's full time flavor!.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ..
Calling all cinnamon roll lovers! We teamed up with CINNABON®, one of our favorite treats, to create our bakery-inspired Breyers® CINNABON®.\n\nBring home the magic of CINNABON® and Breyers® with swirls of gooey cinnamon roll flavor and delicious dough bites in a sweet cinnamon flavored base. It’s a twist on your classic CINNABON® cinnamon roll that will take your senses on a tasty trip.\n\nNot only delicious, but also made with high quality ingredients like fresh cream, sugar and milk. In fact, our milk and cream is 100% Grade A from American cows not treated with artificial growth hormones*. We use colors and flavors from natural sources and only sustainably farmed fruit and vanilla**. Our commitment to using high quality ingredients goes back more than 150 years to give you a great tasting dessert.\n\nTry out our Breyers® CINNABON® and let us know what you think at !\n\n*The FDA states that no significant difference has been shown between dairy derived from rBST-treated and non-rBST-treated cows. ** Our product, before the inclusion of any candies, cookies, sauces or fruit from other suppliers, will fully abide by this claim. Raspberries are not sustainably farmed.    1
Watching your grams of sugar or carbs? Try our Breyers® CarbSmart™ Caramel Swirl Bars, with 60 calories, 4g net carbs, 4g sugar, and 3g fiber+ per serving! Sometimes, you just need a treat that you can grab and go and maybe even eat in four bites!\n\nWe start with fresh 100% Grade A cream from American cows not treated with artificial growth hormones*. Our fruit and vanilla is sustainably farmed and we only use colors and flavors from natural sources. So, while you’re walking around and enjoying the 4 grams of sugar of a Breyers® CarbSmart™ Caramel Swirl Bar, you know that even after more than 150 years, we’re following the spirit of William’s Pledge of Purity.\n\nWe hope that you give our Caramel Swirl Bars a try and see if you love them! Or, give our other flavors a try like Almond Bars, Vanilla Bars, and our Fudge Bars!\n\n*The FDA states that no significant difference has been shown between dairy derived from rBST-treated and non-rBST-treated cows. +SEE NUTRITION FACTS FOR MORE INFORMATION +NET CARBS ARE CALCULATED BY SUBTRACTING TOTAL DIETARY FIBER AND SUGAR ALCOHOL FROM TOTAL CARBOHYDRATES                                                                              1
Calling all S'mores lovers! Make sure you don't miss out on our Layered Dessert S'mores. We start with smooth Breyers® and stir in sweet graham pieces between two layers of chocolate with marshmallows.\n\nNot only delicious, but also made with high quality ingredients like fresh cream, sugar and milk. In fact, our milk and cream is 100% Grade A from American cows not treated with artificial growth hormones*. Our commitment to using high quality ingredients goes back more than 150 years to give you a great tasting dessert.\n\nTry Breyers® Layered Dessert S'mores and let us know what you think at !\n\n*The FDA states that no significant difference has been shown between dairy derived from rBST-treated and non-rBST-treated cows.                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
Love peach cobbler topped with Breyers®? Then make sure you don't miss out on our Limited Edition Peach Cobbler Layered Dessert. We start with smooth Breyers® and stir in real buttery shortbread pieces between two layers of peach with peach pieces. The experience of peach cobbler topped with Breyers, all in one scoop!\n\nNot only delicious, but also made with high quality ingredients like fresh cream, sugar and milk. In fact, our milk and cream is 100% Grade A from American cows not treated with artificial growth hormones*. We use colors and flavors from natural sources and only sustainably farmed fruit and vanilla**.\n\nTry Breyers® Layered Dessert Peach Cobbler and let us know what you think at !\n\n*The FDA states that no significant difference has been shown between dairy derived from rBST-treated and non-rBST-treated cows. **In Breyers® Cookies & Candies, our product, before the inclusion of other cookies, candies, sauces or fruit from other suppliers, will abide by this claim. Raspberries are not sustainably farmed.                                                                                                                                                         1
Love brownie cheesecake? What about Breyers®? Now you can get both delicious desserts in just one scoop! We start with smooth cheesecake Breyers® and stir in real cheesecake pieces and surround it by two layers of chocolate with brownies.\n\nNot only delicious, but also made with high quality ingredients like fresh cream, sugar and milk. In fact, our milk and cream is 100% Grade A from American cows not treated with artificial growth hormones*. We use colors and flavors from natural sources and only sustainably farmed fruit and vanilla**. Our commitment to using high quality ingredients goes back more than 150 years to give you a great tasting dessert.\n\nMake sure you don't miss out on our Breyers® Layered Dessert Brownie Cheesecake. Try it and let us know what you think at !\n\n*The FDA states that no significant difference has been shown between dairy derived from rBST-treated and non-rBST-treated cows. **Our product, before the inclusion of any candies, cookies, sauces or fruit from other suppliers, will fully abide by this claim. Raspberries are not sustainably farmed.                                                                                                    1
Name: count, Length: 237, dtype: int64

ingredients
MILK, SUGAR, SKIM MILK, CREAM, WATER, COCONUT OIL, CORN SYRUP, WHOLE EGG AND EGG YOLK, COCOA PROCESSED WITH ALKALI, ENRICHED WHEAT FLOUR (WHEAT FLOUR, NIACIN, REDUCED IRON, THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID), DEXTROSE, PALM OIL AND SOYBEAN OIL, BAKING SODA, VANILLA EXTRACT, CAROB BEAN GUM, SUNFLOWER LECITHIN, SEA SALT, SOY LECITHIN, NATURAL FLAVOR, DRIED CANE SYRUP, COCOA, BUTTER (CREAM, SALT), GUAR GUM, CORN STARCH, SALT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              2
CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, BROWN SUGAR, SUGAR, MILK, WHEAT FLOUR, EGG YOLKS, CORN SYRUP, EGGS, BUTTER (CREAM, SALT), BUTTEROIL, PECTIN, SEA SALT, SOYBEAN OIL, VANILLA EXTRACT, GUAR GUM, SOY LECITHIN, BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORN STARCH, MONOCALCIUM PHOSPHATE), BAKING SODA, SALT, CARRAGEENAN, LACTASE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1
CREAM, LIQUID SUGAR (SUGAR, WATER), SKIM MILK, WATER, SUGAR, COCOA (PROCESSED WITH ALKALI), POTATO, COCONUT OIL, CORN SYRUP SOLIDS, SOYBEAN OIL, EGG YOLKS, RICE STARCH, SUNFLOWER OIL, BARLEY MALT, COCOA POWDER, WHEAT FLOUR, MILK, SALT, SOY LECITHIN, YEAST EXTRACT, NATURAL FLAVOR, GUAR GUM, SEA SALT, MILKFAT, VANILLA EXTRACT, ENZYMES, CARRAGEENAN, BAKING SODA. CONTAINS MILK, EGGS, WHEAT AND SOY                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, SUGAR, PEANUTS, WHEAT FLOUR, CANOLA OIL, EGG YOLKS, CORN STARCH, PEANUT OIL, COCOA POWDER, SALT, SOYBEAN OIL, INVERT CANE SUGAR, MILK FAT, EGGS, EGG WHITES, GUAR GUM, SOY LECITHIN, TAPIOCA STARCH, BAKING SODA, CARRAGEENAN, VANILLA EXTRACT, BARLEY MALT, MALTED BARLEY FLOUR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1
CREAM, SKIM MILK, WATER, LIQUID SUGAR (SUGAR, WATER), SUGAR, CANOLA OIL, SOYBEAN OIL, EGG YOLKS, CORN SYRUP, WHEAT FLOUR, COCONUT OIL, CORN STARCH, COCOA (PROCESSED WITH ALKALI), CORN SYRUP SOLIDS, COCOA, GRAHAM FLOUR, SALT, EGG WHITES, BUTTEROIL, TAPIOCA STARCH, GUAR GUM, SOY LECITHIN, BAKING SODA, NATURAL FLAVOR, MOLASSES, HONEY, VANILLA EXTRACT, PECTIN, CARAMELIZED SUGAR SYRUP, CARRAGEENAN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ..
MILK, CORN SYRUP, SUGAR, BROWN SUGAR, SOYBEAN OIL, WATER, BUTTER, CREAM, SALT, CORN SYRUP, SPICE, SALT, SOYBEAN LECITHIN, VANILLA EXTRACT, DRIED CANE SYRUP, UNBLEACHED UNENRICHED WHEAT FLOUR, COCONUT OIL, WATER, BUTTER, CREAM, SALT, MOLASSES, SODIUM BICARBONATE, SPICE, CORN SYRUP, SOY LECITHIN, SALT, FRUCTOSE, COCONUT OIL, WHEY, CREAM, VEGETABLE GUMS, GUAR, CAROB BEAN, MONO AND DIGLYCERIDES, NATURAL FLAVOR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
MILK, WATER, CARAMEL SWIRL, SUGAR, WATER, CORN SYRUP, HIGH FRUCTOSE CORN SYRUP, NONFAT MILK SOLIDS, BUTTER, CREAM, SALT, SALT, MOLASSES, PECTIN, SOY LECITHIN, NATURAL FLAVOR, POTASSIUM SORBATE (PRESERVATIVE), SODIUM CITRATE, LACTIC ACID, MALTITOL SYRUP, POLYDEXTROSE, COCONUT OIL, WHEY, GLYCERIN, CREAM, SOLUBLE CORN FIBER, VEGETABLE GUMS, CAROB BEAN GUM, GUAR GUM, CARAMEL (FOR COLOR), MONO AND DIGLYCERIDES, NATURAL FLAVOR, ACESULFAME POTASSIUM, SUCRALOSE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
MILK, CORN SYRUP, SUGAR, WHEAT FLOUR, BUTTER, CREAM (MILK), SALT, PALM OIL, CORN SYRUP, NONFAT MILK, WATER, RICE FLOUR, NATURAL FLAVORS, SALT, WHEAT FLOUR, SUGAR, PALM OIL, MOLASSES, SPICES, SALT, BAKING SODA, NATURAL FLAVOR, SOYBEAN LECITHIN, FRUCTOSE, COCONUT OIL, DUTCHED COCOA (PROCESSED WITH ALKALI), WHEY, CREAM, VEGETABLE GUMS, GUAR, CAROB BEAN, MONO AND DIGLYCERIDES, NATURAL FLAVOR, VANILLA EXTRACT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1
MILK, CORN SYRUP, ENRICHED WHEAT FLOUR, WHEAT FLOUR, NIACIN, REDUCED IRON, THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID, SUGAR, BUTTER, CREAM, SALT, CANOLA OIL, SKIM MILK POWDER, SALT, SODIUM BICARBONATE, PEACHES, FRUCTOSE, COCONUT OIL, SUGAR, WHEY, CREAM, VEGETABLE GUMS, GUAR GUM, CAROB BEAN GUM, TARA GUM, MONO AND DIGLYCERIDES, NATURAL FLAVOR, VANILLA BEANS, ANNATTO (FOR COLOR), VANILLA EXTRACT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
MILK, CORN SYRUP, SUGAR, ENRICHED WHEAT FLOUR, WHEAT FLOUR, NIACIN, REDUCED IRON, THIAMINE MONONITRATE (VITAMIN B1), RIBOFLAVIN (VITAMIN B2), FOLIC ACID, POWDERED SUGAR, SUGAR, CORNSTARCH, COCOA (PROCESSED WITH ALKALI), WATER, PALM KERNEL OIL, SOYBEAN OIL, NONFAT DRY MILK, SOY LECITHIN (EMULSIFIER), NATURAL FLAVORS, FRUCTOSE, CHEESECAKE PIECES WITH GRAHAM CRUST, CREAM CHEESE, PASTEURIZED MILK, CREAM, CHEESE CULTURES, SALT, CAROB BEAN GUM, SUGAR, PASTEURIZED WHOLE EGGS, GRAHAM CRUMB, UNBLEACHED UNENRICHED WHEAT FLOUR, WHOLE WHEAT/GRAHAM FLOUR, SUGAR, CANOLA OIL, MOLASSES, HONEY, SALT, SODIUM BICARBONATE, CORNSTARCH, PALM OIL, NATURAL FLAVOR, SWEETENED LEMON ZEST, LEMON PEEL, SUGAR, LEMON OIL, GUAR GUM, COCONUT OIL, DUTCHED COCOA (PROCESSED WITH ALKALI), WHEY, CREAM, CREAM CHEESE, PASTEURIZED MILK, CREAM, CHEESE CULTURES, SALT, CAROB BEAN GUM, DRIED CANE SYRUP, VEGETABLE GUMS, GUAR, CAROB BEAN GUM, MONO AND DIGLYCERIDES, NATURAL FLAVOR, SALT, PECTIN, SUGAR, ANNATTO (FOR COLOR)    1
Name: count, Length: 240, dtype: int64

## Explore and preprocess the data

### Subtask:
Handle missing values in the 'subhead' and 'description' columns.

**Reasoning**:
Fill the missing values in the 'subhead' and 'description' columns with the specified placeholder strings as requested by the subtask.

In [5]:
products_df['subhead'] = products_df['subhead'].fillna('No subhead available')
products_df['description'] = products_df['description'].fillna('No description available')
display(products_df.isnull().sum())

brand           0
key             0
name            0
subhead         0
description     0
rating          0
rating_count    0
ingredients     0
dtype: int64

## Explore and preprocess the data

### Subtask:
Further explore and preprocess the data by analyzing the unique values in the 'brand', 'key', 'name', and 'ingredients' columns to identify potential inconsistencies, variations, or patterns that may require cleaning or transformation before feature engineering and model training.

**Reasoning**:
Print the number of unique values for the specified columns and then print the unique values for 'brand' and the first 20 unique values for 'ingredients'.

In [6]:
print("Number of unique values:")
print(f"Brand: {products_df['brand'].nunique()}")
print(f"Key: {products_df['key'].nunique()}")
print(f"Name: {products_df['name'].nunique()}")
print(f"Ingredients: {products_df['ingredients'].nunique()}")

print("\nUnique values in 'brand' column:")
print(products_df['brand'].unique())

print("\nFirst 20 unique values in 'ingredients' column:")
print(products_df['ingredients'].unique()[:20])

Number of unique values:
Brand: 4
Key: 241
Name: 240
Ingredients: 240

Unique values in 'brand' column:
['bj' 'hd' 'talenti' 'breyers']

First 20 unique values in 'ingredients' column:
['CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, BROWN SUGAR, SUGAR, MILK, WHEAT FLOUR, EGG YOLKS, CORN SYRUP, EGGS, BUTTER (CREAM, SALT), BUTTEROIL, PECTIN, SEA SALT, SOYBEAN OIL, VANILLA EXTRACT, GUAR GUM, SOY LECITHIN, BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORN STARCH, MONOCALCIUM PHOSPHATE), BAKING SODA, SALT, CARRAGEENAN, LACTASE'
 'CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, SUGAR, PEANUTS, WHEAT FLOUR, CANOLA OIL, EGG YOLKS, CORN STARCH, PEANUT OIL, COCOA POWDER, SALT, SOYBEAN OIL, INVERT CANE SUGAR, MILK FAT, EGGS, EGG WHITES, GUAR GUM, SOY LECITHIN, TAPIOCA STARCH, BAKING SODA, CARRAGEENAN, VANILLA EXTRACT, BARLEY MALT, MALTED BARLEY FLOUR'
 'CREAM, LIQUID SUGAR (SUGAR, WATER), SKIM MILK, WATER, SUGAR, COCOA (PROCESSED WITH ALKALI), POTATO, COCONUT OIL, CORN SYRUP SOLIDS, SOYBEAN OIL, EGG YOLKS, RICE STARCH, SUNFLOWER OIL, BARLEY MALT, COCOA POWDER, WHEAT FLOUR, MILK, SALT, SOY LECITHIN, YEAST EXTRACT, NATURAL FLAVOR, GUAR GUM, SEA SALT, MILKFAT, VANILLA EXTRACT, ENZYMES, CARRAGEENAN, BAKING SODA. CONTAINS MILK, EGGS, WHEAT AND SOY'
 'CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER),  WATER, CORN SYRUP, COCONUT OIL, SUGAR, DRIED CANE SYRUP, EGG YOLKS, WHEAT FLOUR, MILK, COCOA, NATURAL FLAVOR, GUAR GUM, SOY LECITHIN, BUTTER OIL, NATURAL FLAVORS, LOCUST BEAN GUM, SALT, CITRIC ACID, VANILLA BEAN SEEDS, SOYBEAN OIL, TAPIOCA STARCH, LACTIC ACID, CARRAGEENAN'
 'CREAM, SKIM MILK, WATER, LIQUID SUGAR (SUGAR, WATER), SUGAR, CANOLA OIL, SOYBEAN OIL, EGG YOLKS, CORN SYRUP, WHEAT FLOUR, COCONUT OIL, CORN STARCH, COCOA (PROCESSED WITH ALKALI), CORN SYRUP SOLIDS, COCOA, GRAHAM FLOUR, SALT, EGG WHITES, BUTTEROIL, TAPIOCA STARCH, GUAR GUM, SOY LECITHIN, BAKING SODA, NATURAL FLAVOR, MOLASSES, HONEY, VANILLA EXTRACT, PECTIN, CARAMELIZED SUGAR SYRUP, CARRAGEENAN'
 'CREAM, LIQUID SUGAR (SUGAR, WATER), SKIM MILK, WATER, SUGAR, WHEAT FLOUR, PEANUTS, COCOA (PROCESSED WITH ALKALI), BROWN SUGAR, EGG YOLKS, COCOA POWDER, PEANUT OIL, SOYBEAN OIL, BUTTER (CREAM, SALT), INVERT CANE SUGAR, SALT, CHOCOLATE LIQUOR, EGGS, TAPIOCA FLOUR, PEANUT FLOUR, PEANUT EXTRACT, VANILLA EXTRACT, EGG WHITES, GUAR GUM, COCOA BUTTER, NATURAL FLAVOR, CARRAGEENAN, SOY LECITHIN, BAKING SODA, MALTED BARLEY FLOUR'
 'CREAM, SKIM MILK, WATER, LIQUID SUGAR (SUGAR, WATER), ROASTED ALMONDS (ALMONDS, PEANUT OIL), DRIED CANE SYRUP, EGG YOLKS, WHEAT FLOUR, COCONUT OIL, BLACKBERRY JUICE CONCENTRATE, BUTTER (CREAM, SALT), SUGAR, COCOA, SOYBEAN OIL, CORN SYRUP, SALT, BUTTEROIL, SOY LECITHIN, VANILLA EXTRACT, EGGS, GUAR GUM, MILK, NATURAL FLAVORS, BAKING SODA, TAPIOCA STARCH, CARRAGEENAN, LACTIC ACID, CITRIC ACID'
 'CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, SUGAR, PEANUTS, COCONUT OIL, BANANA PUREE, COCOA (PROCESSED WITH ALKALI), EGG YOLKS, MILK, NONFAT MILK, GUAR GUM, NATURAL FLAVORS, LEMON JUICE CONCENTRATE, SALT, COCOA, SOY LECITHIN, VANILLA EXTRACT, CARRAGEENAN'
 'CREAM, LIQUID SUGAR (SUGAR, WATER), SKIM MILK, WATER, SUGAR, WHEAT FLOUR, DRIED CANE SYRUP, COCOA (PROCESSED WITH ALKALI), EGG YOLKS, COCOA POWDER, SOYBEAN OIL, INVERT SUGAR, BUTTER (CREAM, SALT), COCONUT OIL, MOLASSES, SALT, EGGS, SPICES, BAKING SODA, CORN SYRUP, SOY LECITHIN, EGG WHITES, GUAR GUM, CINNAMON, NATURAL FLAVOR, CARRAGEENAN, VANILLA EXTRACT, MALTED BARLEY FLOUR'
 'CREAM, LIQUID SUGAR (SUGAR, WATER), SKIM MILK, WATER, SUGAR, COCOA (PROCESSED WITH ALKALI), SOYBEAN OIL, COCONUT OIL, WHEAT FLOUR, CORN SYRUP, ALMONDS, BUTTER (CREAM, SALT), EGG YOLKS, VANILLA EXTRACT, SALT, NATURAL FLAVORS, EGGS, GUAR GUM, COCOA, SOY LECITHIN, MILK, BAKING SODA, CARRAGEENAN'
 'CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, CORN SYRUP, DRIED CANE SYRUP, SUGAR, WHEAT FLOUR, EGG YOLKS, COCONUT OIL, BUTTER (CREAM, SALT), COCOA, VANILLA EXTRACT, NATURAL FLAVOR, SOY LECITHIN, SALT, BUTTER OIL, MILK, CARRAGEENAN, GUAR GUM, SOYBEAN OIL, BAKING SODA'
 'CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, CORN SYRUP, PECANS, BUTTER (CREAM, SALT), WHEAT FLOUR, EGG YOLKS, SUGAR, DRIED CANE SYRUP, WHISKEY, DRY MALT EXTRACT (BARLEY), SOYBEAN OIL, SALT, EGGS, CARAMEL COLOR, PEANUT OIL, GUAR GUM, BAKING SODA, CARRAGEENAN, SOY LECITHIN. MAY CONTAIN OTHER TREE NUTS'
 'CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, SUGAR, COFFEE EXTRACT, COCONUT OIL, EGG YOLKS, COCOA PROCESSED WITH ALKALI, WHEAT FLOUR, BUTTER (CREAM, SALT), CHOCOLATE LIQUOR, CORN SYRUP, COCOA POWDER, CANOLA OIL, GUAR GUM, SOY LECITHIN, SALT, CARRAGEENAN, NATURAL FLAVOR, MILK FAT, BAKING SODA, VANILLA EXTRACT'
 'CREAM, SKIM MILK, WATER, LIQUID SUGAR (SUGAR, WATER), SUGAR, CORN SYRUP, CANOLA OIL, CREAM CHEESE (PASTEURIZED MILK, CREAM, CHEESE CULTURES, SALT, CAROB BEAN GUM), COCONUT OIL, EGG YOLKS, WHEAT FLOUR, DRIED CANE SYRUP, SOYBEAN OIL, GRAHAM FLOUR, EGGS, COCOA (PROCESSED WITH ALKALI), NATURAL FLAVORS, COCOA, GUAR GUM, BUTTEROIL, MILK PROTEIN CONCENTRATE, CORN STARCH, SALT, SOY LECITHIN, TAPIOCA STARCH, PECTIN, CARAMELIZED SUGAR SYRUP, BAKING SODA, MOLASSES, HONEY, CARRAGEENAN, VANILLA EXTRACT'
 'CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, CHERRIES, SUGAR, EGG YOLKS, COCONUT OIL, COCOA (PROCESSED WITH ALKALI), FRUIT AND VEGETABLE CONCENTRATES (COLOR), COCOA POWDER, GUAR GUM, NATURAL FLAVORS, LEMON JUICE CONCENTRATE, CARRAGEENAN, MILK FAT, SOY LECITHIN'
 'CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, SUGAR, COCONUT OIL, EGG YOLKS, BUTTER (CREAM, SALT), COFFEE, WHEAT FLOUR, MILK PROTEIN CONCENTRATE, COCOA (PROCESSED WITH ALKALI), SOYBEAN OIL, GUAR GUM, NATURAL FLAVOR, SALT, CORN STARCH, CANOLA OIL, RUM, SOY LECITHIN, CHOCOLATE, BAKING SODA, CARRAGEENAN'
 'CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, WHEAT FLOUR, SUGAR, BROWN SUGAR, EGG YOLKS, BUTTER (CREAM, SALT), EXPELLER PRESSED SOYBEAN OIL, EGGS, COCONUT OIL, CHOCOLATE LIQUOR, VANILLA EXTRACT, COCOA (PROCESSED WITH ALKALI), COCOA POWDER, SALT, MOLASSES, GUAR GUM, COCOA BUTTER, NATURAL FLAVOR, CARRAGEENAN, MILK FAT, SOY LECITHIN'
 'CREAM, LIQUID SUGAR (SUGAR, WATER), SKIM MILK, WATER, SUGAR, COCOA (PROCESSED WITH ALKALI), WHEAT FLOUR, COCOA POWDER, SOYBEAN OIL, EGG YOLKS, INVERT CANE SUGAR, EGGS, EGG WHITES, GUAR GUM, SALT, CARRAGEENAN, VANILLA EXTRACT, MALTED BARLEY FLOUR, SODIUM BICARBONATE'
 'CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, CORN SYRUP, WHEAT FLOUR, POWDERED SUGAR (CANE SUGAR, CORNSTARCH), SUGAR, EGG YOLKS, COCOA (PROCESSED WITH ALKALI), BUTTER (CREAM, SALT), BARLEY MALT, TAPIOCA SYRUP, EGG WHITES, MILK, COCOA, SEA SALT, GUAR GUM, NATURAL FLAVOR, PECTIN, VANILLA EXTRACT, ENZYMES, CARRAGEENAN, SALT, BAKING SODA'
 'CREAM, LIQUID SUGAR (SUGAR, WATER), SKIM MILK, WATER, COCOA (PROCESSED WITH ALKALI), WHEAT FLOUR, SUGAR, SOYBEAN OIL, BROWN SUGAR, EGG YOLKS, CHOCOLATE LIQUOR, COCOA, HONEY, GUAR GUM, COCOA BUTTER, VANILLA EXTRACT, SALT, BAKING SODA, NATURAL FLAVORS, SOY LECITHIN, CARRAGEENAN']

## Feature engineering

### Subtask:
Create a new feature based on the length of the 'description' column.

**Reasoning**:
Calculate the length of the text in the 'description' column and store it in a new column named 'description_length', then display the first 5 rows of the updated DataFrame.

In [7]:
products_df['description_length'] = products_df['description'].apply(len)
display(products_df.head())

,brand,key,name,subhead,description,rating,rating_count,ingredients,description_length
0,bj,0_bj,Salted Caramel Core,Sweet Cream Ice Cream with Blonde Brownies & a...,Find your way to the ultimate ice cream experi...,3.7,208,"CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER),...",227
1,bj,1_bj,Netflix & Chilll'd™,Peanut Butter Ice Cream with Sweet & Salty Pre...,There’s something for everyone to watch on Net...,4.0,127,"CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER),...",285
2,bj,2_bj,Chip Happens,A Cold Mess of Chocolate Ice Cream with Fudge ...,Sometimes “chip” happens and everything’s a me...,4.7,130,"CREAM, LIQUID SUGAR (SUGAR, WATER), SKIM MILK,...",263
3,bj,3_bj,Cannoli,Mascarpone Ice Cream with Fudge-Covered Pastry...,As a Limited Batch that captured the rapture o...,3.6,70,"CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER),...",232
4,bj,4_bj,Gimme S’more!™,Toasted Marshmallow Ice Cream with Chocolate C...,It’s a gimme: there’s always room for s’more. ...,4.5,281,"CREAM, SKIM MILK, WATER, LIQUID SUGAR (SUGAR, ...",211

## Feature engineering

### Subtask:
Create a new feature based on the presence of specific keywords in the 'ingredients' column.

**Reasoning**:
Define the list of keywords and create a new column 'keyword_count' initialized to 0. Then, iterate through the DataFrame, count the occurrences of keywords in the 'ingredients' column for each row, update the 'keyword_count' column, and finally display the first 5 rows to verify the new column.

In [8]:
keywords = ['chocolate', 'vanilla', 'strawberry', 'nuts', 'caramel', 'cookie dough']
products_df['keyword_count'] = 0

for index, row in products_df.iterrows():
    count = sum(keyword.lower() in row['ingredients'].lower() for keyword in keywords)
    products_df.loc[index, 'keyword_count'] = count

display(products_df.head())

,brand,key,name,subhead,description,rating,rating_count,ingredients,description_length,keyword_count
0,bj,0_bj,Salted Caramel Core,Sweet Cream Ice Cream with Blonde Brownies & a...,Find your way to the ultimate ice cream experi...,3.7,208,"CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER),...",227,1
1,bj,1_bj,Netflix & Chilll'd™,Peanut Butter Ice Cream with Sweet & Salty Pre...,There’s something for everyone to watch on Net...,4.0,127,"CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER),...",285,2
2,bj,2_bj,Chip Happens,A Cold Mess of Chocolate Ice Cream with Fudge ...,Sometimes “chip” happens and everything’s a me...,4.7,130,"CREAM, LIQUID SUGAR (SUGAR, WATER), SKIM MILK,...",263,1
3,bj,3_bj,Cannoli,Mascarpone Ice Cream with Fudge-Covered Pastry...,As a Limited Batch that captured the rapture o...,3.6,70,"CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER),...",232,1
4,bj,4_bj,Gimme S’more!™,Toasted Marshmallow Ice Cream with Chocolate C...,It’s a gimme: there’s always room for s’more. ...,4.5,281,"CREAM, SKIM MILK, WATER, LIQUID SUGAR (SUGAR, ...",211,2

## Choose a model

### Subtask:
Select an appropriate machine learning model for regression to predict the ice cream ratings.

## Train the model

### Subtask:
Split the data into training and testing sets and train a Random Forest Regressor model on the training data.

**Reasoning**:
Split the data into training and testing sets and train a Random Forest Regressor model.

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

X = products_df[['description_length', 'keyword_count']]
y = products_df['rating']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestRegressor(random_state=42)

model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

## Evaluate the model

### Subtask:
Evaluate the trained Random Forest Regressor model's performance on the testing data using relevant metrics like Mean Squared Error (MSE), Root Mean Squared Error (RMSE), and R-squared.

**Reasoning**:
Import the necessary metrics, make predictions, calculate MSE, RMSE, and R-squared, and print the results to evaluate the model's performance.

In [10]:
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R-squared (R2): {r2}")

Mean Squared Error (MSE): 0.4842262991816409
Root Mean Squared Error (RMSE): 0.6958637073318603
R-squared (R2): -0.4998159709165868

## Predict ratings

### Subtask:
Use the trained Random Forest Regressor model to predict ice cream ratings on the test dataset (`X_test`).

**Reasoning**:
Use the trained Random Forest Regressor model to make predictions on the test dataset and store the predictions in `y_pred`.

In [11]:
y_pred = model.predict(X_test)

## Summary:

### Data Analysis Key Findings

*   The dataset contains information on ice cream products, including brand, name, subhead, description, ingredients, rating, and rating count.
*   Missing values were identified in the 'subhead' (184) and 'description' (4) columns and were imputed with placeholder text.
*   The dataset includes four unique brands: 'bj', 'hd', 'talenti', and 'breyers'.
*   There is a near one-to-one mapping between the 'key', 'name', and 'ingredients' columns.
*   The 'ingredients' column contains detailed ingredient lists with variations in formatting.
*   Two new features were engineered: 'description\_length' (length of the description) and 'keyword\_count' (number of specific keywords found in ingredients).
*   A Random Forest Regressor model was chosen and trained to predict ice cream ratings based on 'description\_length' and 'keyword\_count'.
*   The model's performance on the test set was evaluated, resulting in an MSE of 0.4842, RMSE of 0.6959, and an R-squared of -0.4998.

### Insights or Next Steps

*   The negative R-squared value suggests that the current features ('description\_length' and 'keyword\_count') are not strong predictors of ice cream ratings, and the model performs worse than simply predicting the mean rating.
*   Future steps should involve exploring more relevant features, potentially derived from the 'ingredients' column using techniques like TF-IDF or embeddings, and incorporating the 'brand' and 'rating\_count' features into the model. More advanced regression models or hyperparameter tuning of the current model could also be explored.

# Task
Predict ice cream ratings using the dataset in the file "products.csv".

## Load the dataset

### Subtask:
Load the `products.csv` file into a pandas DataFrame.

**Reasoning**:
Load the `products.csv` file into a pandas DataFrame as requested by the subtask.

In [12]:
products_df = pd.read_csv('/root/.cache/kagglehub/datasets/tysonpo/ice-cream-dataset/versions/3/combined/products.csv')

## Explore and preprocess the data

### Subtask:
Analyze the data types, check for missing values, and perform necessary data cleaning and transformations. This may include handling categorical variables, scaling numerical features, and addressing any inconsistencies.

**Reasoning**:
Display the data types, check for missing values, display descriptive statistics for numerical columns, and display unique values and their counts for categorical columns to understand the dataset's structure and identify areas for cleaning and transformation.

In [13]:
display(products_df.info())
display(products_df.isnull().sum())
display(products_df.describe())
for col in products_df.select_dtypes(include='object').columns:
    display(products_df[col].value_counts())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         241 non-null    object
 1   key           241 non-null    object
 2   name          241 non-null    object
 3   subhead       57 non-null     object
 4   description   237 non-null    object
 5   rating        241 non-null    float64
 6   rating_count  241 non-null    int64
 7   ingredients   241 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 15.2+ KB

None

brand             0
key               0
name              0
subhead         184
description       4
rating            0
rating_count      0
ingredients       0
dtype: int64

           rating  rating_count
count  241.000000    241.000000
mean     4.223237     90.016598
std      0.620383    111.349449
min      1.200000      2.000000
25%      4.000000     28.000000
50%      4.400000     59.000000
75%      4.700000    112.000000
max      5.000000    983.000000

brand
hd         70
breyers    69
bj         57
talenti    45
Name: count, dtype: int64

key
0_bj          1
1_bj          1
2_bj          1
3_bj          1
4_bj          1
             ..
64_breyers    1
65_breyers    1
66_breyers    1
67_breyers    1
68_breyers    1
Name: count, Length: 241, dtype: int64

name
Chocolate Chip Cookie Dough           2
Salted Caramel Core                   1
Chip Happens                          1
Netflix & Chilll'd™                   1
Gimme S’more!™                        1
                                     ..
CINNABON®                             1
CarbSmart™ Caramel Swirl Bar          1
Layered Dessert S'mores               1
Layered Dessert Peach Cobbler         1
Layered Dessert Brownie Cheesecake    1
Name: count, Length: 240, dtype: int64

subhead
Sweet Cream Ice Cream with Blonde Brownies & a Salted Caramel Core                                                                                           1
Peanut Butter Ice Cream with Sweet & Salty Pretzel Swirls & Fudge Brownies                                                                                   1
A Cold Mess of Chocolate Ice Cream with Fudge Chips & Crunchy Potato Chip Swirls                                                                             1
Mascarpone Ice Cream with Fudge-Covered Pastry Shell Pieces & Mascarpone Swirls                                                                              1
Toasted Marshmallow Ice Cream with Chocolate Cookie Swirls, Graham Cracker Swirls & Fudge Flakes                                                             1
Chocolate & Peanut Butter Ice Creams Mixed with Gobs of Peanut Butter Cookie Dough & Fudge Brownies                                                          1
Blackberry & Mascarpone Ice Creams with Shortbread Cookies & Fudge-Covered Almonds                                                                           1
Chocolate & Banana Ice Creams with Mini Peanut Butter Cups                                                                                                   1
Cinnamon & Chocolate Ice Creams with Gobs of Cinnamon Bun Dough & Spicy Fudge Brownies                                                                       1
A Universe of Milk Chocolate Ice Cream with Fudge Cows & Toffee Meteor Clusters Orbiting a Sugar Cookie Dough Core                                           1
Vanilla Ice Cream with Fudge-Covered Waffle Cone Pieces & a Caramel Swirl                                                                                    1
Buttery Bourbon Ice Cream with Pecans, Shortbread Cookie Pieces & a Whiskey Caramel Swirl                                                                    1
Coffee Ice Cream with Fudge Chunks & a Brownie Batter Swirl                                                                                                  1
Caramel Cheesecake Ice Cream with Cheesecake Pieces & Chocolate Cookie Swirls                                                                                1
Cherry Ice Cream with Cherries & Fudge Flakes                                                                                                                1
Cold Brew Coffee Ice Cream with Chocolate Cookie-Covered Coffee Liqueur Truffles & Fudge Swirls                                                              1
Vanilla Ice Cream with Gobs of Chocolate Chip Cookie Dough                                                                                                   1
Chocolate Ice Cream with Fudge Brownies                                                                                                                      1
Chocolate Malt Milkshake Ice Cream With Salted Fudge Pieces & Marshmallow Swirls                                                                             1
Chocolate Ice Cream with Chocolate Cookies & Swirls of Chocolate Pudding Ice Cream                                                                           1
Vanilla Malt Ice Cream with Peanutty Fudge-Covered Pretzels with Fudge & Peanut Buttery Swirls                                                               1
Banana Ice Cream with Fudge Chunks & Walnuts                                                                                                                 1
Caramel Ice Cream with Cinnamon Bun Dough & a Cinnamon Streusel Swirl                                                                                        1
Coffee Ice Cream with Espresso Bean Fudge Chunks                                                                                                             1
Coffee Ice Cream with Fudge-Covered Toffee Pieces                                                                                                            1
Cold Brew & Sweet Cream Ice Creams with Salted Caramel Swirls                                                                                                1
A Collision of Chocolate & Vanilla Ice Creams mixed with Peanut Butter Cups, Fudge-Covered Toffee Pieces, White Chocolatey Chunks & Fudge-Covered Almonds    1
Chocolate Ice Cream with Crunchy Pretzel Swirls, Marshmallow Swirls & Fudge-Covered Almonds                                                                  1
Chocolate & Vanilla Ice Creams mixed with Gobs of Chocolate Chip Cookie Dough & Fudge Brownies                                                               1
Vanilla Ice Cream with Chocolate Sandwich Cookies & Chocolate Cookie Swirls                                                                                  1
Vanilla Ice Cream with a Chocolate Cookie Swirl, Chocolate Chip & Chocolate Chocolate Chip Cookies                                                           1
Peppermint Ice Cream with Chocolate Sandwich Cookies                                                                                                         1
Dark Chocolate Mint Ice Cream with Marshmallow Swirls & Chocolate Cookie Swirls                                                                              1
Chocolate Ice Cream with White & Dark Fudge Chunks, Pecans, Walnuts & Fudge-Covered Almonds                                                                  1
Buttery Brown Sugar Ice Cream with Fudge Flakes & Oatmeal Cinnamon Cookie Swirls                                                                             1
Peanut Butter Ice Cream with Peanut Butter Cups                                                                                                              1
Milk Chocolate Ice Cream with Peanut Buttery Swirls & Chocolate Cookie Swirls                                                                                1
Chocolate Ice Cream with Gooey Marshmallow Swirls, Caramel Swirls & Fudge Fish                                                                               1
Pistachio Ice Cream with Lightly Roasted Pistachios                                                                                                          1
Pumpkin Cheesecake Ice Cream with a Graham Cracker Swirl                                                                                                     1
Blueberry & Raspberry Ice Cream swirled with Vanilla Ice Cream with Strawberries & Shortbread Pieces                                                         1
Chocolate Ice Cream with Fudge Chunks, Toasted Marshmallow & Graham Cracker Swirls                                                                           1
Vanilla Bean Ice Cream with Roasted Almond Slivers, Fudge Flakes & a Salted Caramel Swirl                                                                    1
Strawberry Cheesecake Ice Cream with Strawberries & a Thick Graham Cracker Swirl                                                                             1
Caramel & Chocolate Ice Creams with Chocolate Cookie Swirls & Gobs of Chocolate Chip Cookie Dough & Peanut Butter Cookie Dough.                              1
Caramel Ice Cream with a Swirl of Caramel & Fudge-Covered Caramel Chunks                                                                                     1
Burnt Caramel Ice Cream with Almonds, Fudge Flakes & Bourbon Caramel Swirls                                                                                  1
Vanilla Ice Cream                                                                                                                                            1
Vanilla Ice Cream with Swirls of Caramel & Fudge                                                                                                             1
Mocha & Caramel Ice Creams with Chocolate Cookies, Fudge Flakes & a Chocolate Cookie Core                                                                    1
Cookie Milk Ice Cream with Fudge Chips & a Chocolate Chip Cookie Dough Core                                                                                  1
Sweet Cream Ice Cream with a hint of Almond flavor & Shortbread Cookies & Cherry Ice Cream with Cherries & a Sugar Cookie Dough Core                         1
Vanilla Ice Cream with Peanut Butter Cookies, Peanut Butter Ice Cream with Fudge Chips & a No Bake Cookie Dough Core                                         1
Chocolate & Vanilla Ice Creams with Fudge Brownies & a Brownie Batter Core                                                                                   1
Chocolate & Cheesecake Ice Creams with Chocolate Cookies & a Cheesecake Core                                                                                 1
Chocolate & Caramel Ice Creams with Fudge Chips & a Soft Caramel Core                                                                                        1
Chocolate & Peanut Butter Ice Creams with Mini Peanut Butter Cups & a Peanut Butter Fudge Core                                                               1
Name: count, dtype: int64

description
Find your way to the ultimate ice cream experience with our Cores. Whether your primal urges lead you to the center of salted caramel or directly to the blonde brownies, you’ll be in total control of your own ice cream destiny.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
There’s something for everyone to watch on Netflix & flavors for everyone to enjoy from Ben & Jerry’s, so we’ve teamed up to bring you a chillaxing new creation that’s certain to satisfy any sweet or salty snack craving. It’s a flavorful world, and everyone is invited to grab a spoon.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
Sometimes “chip” happens and everything’s a mess, but we Nailed It! with this chip-filled limited batch. When smooth chocolate ice cream meets fudge chips & salty swirls, they pack a serious one-two crunch. The best part? There won’t be anything left to clean up.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
As a Limited Batch that captured the rapture of the classic Sicilian dessert, our Cannoli captivated fans like no other Cannoli could. Now that it’s a full-time flavor, you and your Cannoli can re-capture the rapture all over again.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1
It’s a gimme: there’s always room for s’more. And we’re pretty sure you’ll want to make s’more room in your freezer for this ‘shmallowy-rich, graham-good-‘n-chocolatey concoction now that it's full time flavor!.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ..
Calling all cinnamon roll lovers! We teamed up with CINNABON®, one of our favorite treats, to create our bakery-inspired Breyers® CINNABON®.\n\nBring home the magic of CINNABON® and Breyers® with swirls of gooey cinnamon roll flavor and delicious dough bites in a sweet cinnamon flavored base. It’s a twist on your classic CINNABON® cinnamon roll that will take your senses on a tasty trip.\n\nNot only delicious, but also made with high quality ingredients like fresh cream, sugar and milk. In fact, our milk and cream is 100% Grade A from American cows not treated with artificial growth hormones*. We use colors and flavors from natural sources and only sustainably farmed fruit and vanilla**. Our commitment to using high quality ingredients goes back more than 150 years to give you a great tasting dessert.\n\nTry out our Breyers® CINNABON® and let us know what you think at !\n\n*The FDA states that no significant difference has been shown between dairy derived from rBST-treated and non-rBST-treated cows. ** Our product, before the inclusion of any candies, cookies, sauces or fruit from other suppliers, will fully abide by this claim. Raspberries are not sustainably farmed.    1
Watching your grams of sugar or carbs? Try our Breyers® CarbSmart™ Caramel Swirl Bars, with 60 calories, 4g net carbs, 4g sugar, and 3g fiber+ per serving! Sometimes, you just need a treat that you can grab and go and maybe even eat in four bites!\n\nWe start with fresh 100% Grade A cream from American cows not treated with artificial growth hormones*. Our fruit and vanilla is sustainably farmed and we only use colors and flavors from natural sources. So, while you’re walking around and enjoying the 4 grams of sugar of a Breyers® CarbSmart™ Caramel Swirl Bar, you know that even after more than 150 years, we’re following the spirit of William’s Pledge of Purity.\n\nWe hope that you give our Caramel Swirl Bars a try and see if you love them! Or, give our other flavors a try like Almond Bars, Vanilla Bars, and our Fudge Bars!\n\n*The FDA states that no significant difference has been shown between dairy derived from rBST-treated and non-rBST-treated cows. +SEE NUTRITION FACTS FOR MORE INFORMATION +NET CARBS ARE CALCULATED BY SUBTRACTING TOTAL DIETARY FIBER AND SUGAR ALCOHOL FROM TOTAL CARBOHYDRATES                                                                              1
Calling all S'mores lovers! Make sure you don't miss out on our Layered Dessert S'mores. We start with smooth Breyers® and stir in sweet graham pieces between two layers of chocolate with marshmallows.\n\nNot only delicious, but also made with high quality ingredients like fresh cream, sugar and milk. In fact, our milk and cream is 100% Grade A from American cows not treated with artificial growth hormones*. Our commitment to using high quality ingredients goes back more than 150 years to give you a great tasting dessert.\n\nTry Breyers® Layered Dessert S'mores and let us know what you think at !\n\n*The FDA states that no significant difference has been shown between dairy derived from rBST-treated and non-rBST-treated cows.                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
Love peach cobbler topped with Breyers®? Then make sure you don't miss out on our Limited Edition Peach Cobbler Layered Dessert. We start with smooth Breyers® and stir in real buttery shortbread pieces between two layers of peach with peach pieces. The experience of peach cobbler topped with Breyers, all in one scoop!\n\nNot only delicious, but also made with high quality ingredients like fresh cream, sugar and milk. In fact, our milk and cream is 100% Grade A from American cows not treated with artificial growth hormones*. We use colors and flavors from natural sources and only sustainably farmed fruit and vanilla**.\n\nTry Breyers® Layered Dessert Peach Cobbler and let us know what you think at !\n\n*The FDA states that no significant difference has been shown between dairy derived from rBST-treated and non-rBST-treated cows. **In Breyers® Cookies & Candies, our product, before the inclusion of other cookies, candies, sauces or fruit from other suppliers, will abide by this claim. Raspberries are not sustainably farmed.                                                                                                                                                         1
Love brownie cheesecake? What about Breyers®? Now you can get both delicious desserts in just one scoop! We start with smooth cheesecake Breyers® and stir in real cheesecake pieces and surround it by two layers of chocolate with brownies.\n\nNot only delicious, but also made with high quality ingredients like fresh cream, sugar and milk. In fact, our milk and cream is 100% Grade A from American cows not treated with artificial growth hormones*. We use colors and flavors from natural sources and only sustainably farmed fruit and vanilla**. Our commitment to using high quality ingredients goes back more than 150 years to give you a great tasting dessert.\n\nMake sure you don't miss out on our Breyers® Layered Dessert Brownie Cheesecake. Try it and let us know what you think at !\n\n*The FDA states that no significant difference has been shown between dairy derived from rBST-treated and non-rBST-treated cows. **Our product, before the inclusion of any candies, cookies, sauces or fruit from other suppliers, will fully abide by this claim. Raspberries are not sustainably farmed.                                                                                                    1
Name: count, Length: 237, dtype: int64

ingredients
MILK, SUGAR, SKIM MILK, CREAM, WATER, COCONUT OIL, CORN SYRUP, WHOLE EGG AND EGG YOLK, COCOA PROCESSED WITH ALKALI, ENRICHED WHEAT FLOUR (WHEAT FLOUR, NIACIN, REDUCED IRON, THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID), DEXTROSE, PALM OIL AND SOYBEAN OIL, BAKING SODA, VANILLA EXTRACT, CAROB BEAN GUM, SUNFLOWER LECITHIN, SEA SALT, SOY LECITHIN, NATURAL FLAVOR, DRIED CANE SYRUP, COCOA, BUTTER (CREAM, SALT), GUAR GUM, CORN STARCH, SALT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              2
CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, BROWN SUGAR, SUGAR, MILK, WHEAT FLOUR, EGG YOLKS, CORN SYRUP, EGGS, BUTTER (CREAM, SALT), BUTTEROIL, PECTIN, SEA SALT, SOYBEAN OIL, VANILLA EXTRACT, GUAR GUM, SOY LECITHIN, BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORN STARCH, MONOCALCIUM PHOSPHATE), BAKING SODA, SALT, CARRAGEENAN, LACTASE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1
CREAM, LIQUID SUGAR (SUGAR, WATER), SKIM MILK, WATER, SUGAR, COCOA (PROCESSED WITH ALKALI), POTATO, COCONUT OIL, CORN SYRUP SOLIDS, SOYBEAN OIL, EGG YOLKS, RICE STARCH, SUNFLOWER OIL, BARLEY MALT, COCOA POWDER, WHEAT FLOUR, MILK, SALT, SOY LECITHIN, YEAST EXTRACT, NATURAL FLAVOR, GUAR GUM, SEA SALT, MILKFAT, VANILLA EXTRACT, ENZYMES, CARRAGEENAN, BAKING SODA. CONTAINS MILK, EGGS, WHEAT AND SOY                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, SUGAR, PEANUTS, WHEAT FLOUR, CANOLA OIL, EGG YOLKS, CORN STARCH, PEANUT OIL, COCOA POWDER, SALT, SOYBEAN OIL, INVERT CANE SUGAR, MILK FAT, EGGS, EGG WHITES, GUAR GUM, SOY LECITHIN, TAPIOCA STARCH, BAKING SODA, CARRAGEENAN, VANILLA EXTRACT, BARLEY MALT, MALTED BARLEY FLOUR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1
CREAM, SKIM MILK, WATER, LIQUID SUGAR (SUGAR, WATER), SUGAR, CANOLA OIL, SOYBEAN OIL, EGG YOLKS, CORN SYRUP, WHEAT FLOUR, COCONUT OIL, CORN STARCH, COCOA (PROCESSED WITH ALKALI), CORN SYRUP SOLIDS, COCOA, GRAHAM FLOUR, SALT, EGG WHITES, BUTTEROIL, TAPIOCA STARCH, GUAR GUM, SOY LECITHIN, BAKING SODA, NATURAL FLAVOR, MOLASSES, HONEY, VANILLA EXTRACT, PECTIN, CARAMELIZED SUGAR SYRUP, CARRAGEENAN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ..
MILK, CORN SYRUP, SUGAR, BROWN SUGAR, SOYBEAN OIL, WATER, BUTTER, CREAM, SALT, CORN SYRUP, SPICE, SALT, SOYBEAN LECITHIN, VANILLA EXTRACT, DRIED CANE SYRUP, UNBLEACHED UNENRICHED WHEAT FLOUR, COCONUT OIL, WATER, BUTTER, CREAM, SALT, MOLASSES, SODIUM BICARBONATE, SPICE, CORN SYRUP, SOY LECITHIN, SALT, FRUCTOSE, COCONUT OIL, WHEY, CREAM, VEGETABLE GUMS, GUAR, CAROB BEAN, MONO AND DIGLYCERIDES, NATURAL FLAVOR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
MILK, WATER, CARAMEL SWIRL, SUGAR, WATER, CORN SYRUP, HIGH FRUCTOSE CORN SYRUP, NONFAT MILK SOLIDS, BUTTER, CREAM, SALT, SALT, MOLASSES, PECTIN, SOY LECITHIN, NATURAL FLAVOR, POTASSIUM SORBATE (PRESERVATIVE), SODIUM CITRATE, LACTIC ACID, MALTITOL SYRUP, POLYDEXTROSE, COCONUT OIL, WHEY, GLYCERIN, CREAM, SOLUBLE CORN FIBER, VEGETABLE GUMS, CAROB BEAN GUM, GUAR GUM, CARAMEL (FOR COLOR), MONO AND DIGLYCERIDES, NATURAL FLAVOR, ACESULFAME POTASSIUM, SUCRALOSE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
MILK, CORN SYRUP, SUGAR, WHEAT FLOUR, BUTTER, CREAM (MILK), SALT, PALM OIL, CORN SYRUP, NONFAT MILK, WATER, RICE FLOUR, NATURAL FLAVORS, SALT, WHEAT FLOUR, SUGAR, PALM OIL, MOLASSES, SPICES, SALT, BAKING SODA, NATURAL FLAVOR, SOYBEAN LECITHIN, FRUCTOSE, COCONUT OIL, DUTCHED COCOA (PROCESSED WITH ALKALI), WHEY, CREAM, VEGETABLE GUMS, GUAR, CAROB BEAN, MONO AND DIGLYCERIDES, NATURAL FLAVOR, VANILLA EXTRACT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1
MILK, CORN SYRUP, ENRICHED WHEAT FLOUR, WHEAT FLOUR, NIACIN, REDUCED IRON, THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID, SUGAR, BUTTER, CREAM, SALT, CANOLA OIL, SKIM MILK POWDER, SALT, SODIUM BICARBONATE, PEACHES, FRUCTOSE, COCONUT OIL, SUGAR, WHEY, CREAM, VEGETABLE GUMS, GUAR GUM, CAROB BEAN GUM, TARA GUM, MONO AND DIGLYCERIDES, NATURAL FLAVOR, VANILLA BEANS, ANNATTO (FOR COLOR), VANILLA EXTRACT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
MILK, CORN SYRUP, SUGAR, ENRICHED WHEAT FLOUR, WHEAT FLOUR, NIACIN, REDUCED IRON, THIAMINE MONONITRATE (VITAMIN B1), RIBOFLAVIN (VITAMIN B2), FOLIC ACID, POWDERED SUGAR, SUGAR, CORNSTARCH, COCOA (PROCESSED WITH ALKALI), WATER, PALM KERNEL OIL, SOYBEAN OIL, NONFAT DRY MILK, SOY LECITHIN (EMULSIFIER), NATURAL FLAVORS, FRUCTOSE, CHEESECAKE PIECES WITH GRAHAM CRUST, CREAM CHEESE, PASTEURIZED MILK, CREAM, CHEESE CULTURES, SALT, CAROB BEAN GUM, SUGAR, PASTEURIZED WHOLE EGGS, GRAHAM CRUMB, UNBLEACHED UNENRICHED WHEAT FLOUR, WHOLE WHEAT/GRAHAM FLOUR, SUGAR, CANOLA OIL, MOLASSES, HONEY, SALT, SODIUM BICARBONATE, CORNSTARCH, PALM OIL, NATURAL FLAVOR, SWEETENED LEMON ZEST, LEMON PEEL, SUGAR, LEMON OIL, GUAR GUM, COCONUT OIL, DUTCHED COCOA (PROCESSED WITH ALKALI), WHEY, CREAM, CREAM CHEESE, PASTEURIZED MILK, CREAM, CHEESE CULTURES, SALT, CAROB BEAN GUM, DRIED CANE SYRUP, VEGETABLE GUMS, GUAR, CAROB BEAN GUM, MONO AND DIGLYCERIDES, NATURAL FLAVOR, SALT, PECTIN, SUGAR, ANNATTO (FOR COLOR)    1
Name: count, Length: 240, dtype: int64

**Reasoning**:
Fill the missing values in the 'subhead' and 'description' columns with the specified placeholder strings as requested by the subtask.

In [14]:
products_df['subhead'] = products_df['subhead'].fillna('No subhead available')
products_df['description'] = products_df['description'].fillna('No description available')
display(products_df.isnull().sum())

brand           0
key             0
name            0
subhead         0
description     0
rating          0
rating_count    0
ingredients     0
dtype: int64

**Reasoning**:
Print the number of unique values for the specified columns and then print the unique values for 'brand' and the first 20 unique values for 'ingredients'.

In [15]:
print("Number of unique values:")
print(f"Brand: {products_df['brand'].nunique()}")
print(f"Key: {products_df['key'].nunique()}")
print(f"Name: {products_df['name'].nunique()}")
print(f"Ingredients: {products_df['ingredients'].nunique()}")

print("\nUnique values in 'brand' column:")
print(products_df['brand'].unique())

print("\nFirst 20 unique values in 'ingredients' column:")
print(products_df['ingredients'].unique()[:20])

Number of unique values:
Brand: 4
Key: 241
Name: 240
Ingredients: 240

Unique values in 'brand' column:
['bj' 'hd' 'talenti' 'breyers']

First 20 unique values in 'ingredients' column:
['CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, BROWN SUGAR, SUGAR, MILK, WHEAT FLOUR, EGG YOLKS, CORN SYRUP, EGGS, BUTTER (CREAM, SALT), BUTTEROIL, PECTIN, SEA SALT, SOYBEAN OIL, VANILLA EXTRACT, GUAR GUM, SOY LECITHIN, BAKING POWDER (SODIUM ACID PYROPHOSPHATE, SODIUM BICARBONATE, CORN STARCH, MONOCALCIUM PHOSPHATE), BAKING SODA, SALT, CARRAGEENAN, LACTASE'
 'CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, SUGAR, PEANUTS, WHEAT FLOUR, CANOLA OIL, EGG YOLKS, CORN STARCH, PEANUT OIL, COCOA POWDER, SALT, SOYBEAN OIL, INVERT CANE SUGAR, MILK FAT, EGGS, EGG WHITES, GUAR GUM, SOY LECITHIN, TAPIOCA STARCH, BAKING SODA, CARRAGEENAN, VANILLA EXTRACT, BARLEY MALT, MALTED BARLEY FLOUR'
 'CREAM, LIQUID SUGAR (SUGAR, WATER), SKIM MILK, WATER, SUGAR, COCOA (PROCESSED WITH ALKALI), POTATO, COCONUT OIL, CORN SYRUP SOLIDS, SOYBEAN OIL, EGG YOLKS, RICE STARCH, SUNFLOWER OIL, BARLEY MALT, COCOA POWDER, WHEAT FLOUR, MILK, SALT, SOY LECITHIN, YEAST EXTRACT, NATURAL FLAVOR, GUAR GUM, SEA SALT, MILKFAT, VANILLA EXTRACT, ENZYMES, CARRAGEENAN, BAKING SODA. CONTAINS MILK, EGGS, WHEAT AND SOY'
 'CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER),  WATER, CORN SYRUP, COCONUT OIL, SUGAR, DRIED CANE SYRUP, EGG YOLKS, WHEAT FLOUR, MILK, COCOA, NATURAL FLAVOR, GUAR GUM, SOY LECITHIN, BUTTER OIL, NATURAL FLAVORS, LOCUST BEAN GUM, SALT, CITRIC ACID, VANILLA BEAN SEEDS, SOYBEAN OIL, TAPIOCA STARCH, LACTIC ACID, CARRAGEENAN'
 'CREAM, SKIM MILK, WATER, LIQUID SUGAR (SUGAR, WATER), SUGAR, CANOLA OIL, SOYBEAN OIL, EGG YOLKS, CORN SYRUP, WHEAT FLOUR, COCONUT OIL, CORN STARCH, COCOA (PROCESSED WITH ALKALI), CORN SYRUP SOLIDS, COCOA, GRAHAM FLOUR, SALT, EGG WHITES, BUTTEROIL, TAPIOCA STARCH, GUAR GUM, SOY LECITHIN, BAKING SODA, NATURAL FLAVOR, MOLASSES, HONEY, VANILLA EXTRACT, PECTIN, CARAMELIZED SUGAR SYRUP, CARRAGEENAN'
 'CREAM, LIQUID SUGAR (SUGAR, WATER), SKIM MILK, WATER, SUGAR, WHEAT FLOUR, PEANUTS, COCOA (PROCESSED WITH ALKALI), BROWN SUGAR, EGG YOLKS, COCOA POWDER, PEANUT OIL, SOYBEAN OIL, BUTTER (CREAM, SALT), INVERT CANE SUGAR, SALT, CHOCOLATE LIQUOR, EGGS, TAPIOCA FLOUR, PEANUT FLOUR, PEANUT EXTRACT, VANILLA EXTRACT, EGG WHITES, GUAR GUM, COCOA BUTTER, NATURAL FLAVOR, CARRAGEENAN, SOY LECITHIN, BAKING SODA, MALTED BARLEY FLOUR'
 'CREAM, SKIM MILK, WATER, LIQUID SUGAR (SUGAR, WATER), ROASTED ALMONDS (ALMONDS, PEANUT OIL), DRIED CANE SYRUP, EGG YOLKS, WHEAT FLOUR, COCONUT OIL, BLACKBERRY JUICE CONCENTRATE, BUTTER (CREAM, SALT), SUGAR, COCOA, SOYBEAN OIL, CORN SYRUP, SALT, BUTTEROIL, SOY LECITHIN, VANILLA EXTRACT, EGGS, GUAR GUM, MILK, NATURAL FLAVORS, BAKING SODA, TAPIOCA STARCH, CARRAGEENAN, LACTIC ACID, CITRIC ACID'
 'CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, SUGAR, PEANUTS, COCONUT OIL, BANANA PUREE, COCOA (PROCESSED WITH ALKALI), EGG YOLKS, MILK, NONFAT MILK, GUAR GUM, NATURAL FLAVORS, LEMON JUICE CONCENTRATE, SALT, COCOA, SOY LECITHIN, VANILLA EXTRACT, CARRAGEENAN'
 'CREAM, LIQUID SUGAR (SUGAR, WATER), SKIM MILK, WATER, SUGAR, WHEAT FLOUR, DRIED CANE SYRUP, COCOA (PROCESSED WITH ALKALI), EGG YOLKS, COCOA POWDER, SOYBEAN OIL, INVERT SUGAR, BUTTER (CREAM, SALT), COCONUT OIL, MOLASSES, SALT, EGGS, SPICES, BAKING SODA, CORN SYRUP, SOY LECITHIN, EGG WHITES, GUAR GUM, CINNAMON, NATURAL FLAVOR, CARRAGEENAN, VANILLA EXTRACT, MALTED BARLEY FLOUR'
 'CREAM, LIQUID SUGAR (SUGAR, WATER), SKIM MILK, WATER, SUGAR, COCOA (PROCESSED WITH ALKALI), SOYBEAN OIL, COCONUT OIL, WHEAT FLOUR, CORN SYRUP, ALMONDS, BUTTER (CREAM, SALT), EGG YOLKS, VANILLA EXTRACT, SALT, NATURAL FLAVORS, EGGS, GUAR GUM, COCOA, SOY LECITHIN, MILK, BAKING SODA, CARRAGEENAN'
 'CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, CORN SYRUP, DRIED CANE SYRUP, SUGAR, WHEAT FLOUR, EGG YOLKS, COCONUT OIL, BUTTER (CREAM, SALT), COCOA, VANILLA EXTRACT, NATURAL FLAVOR, SOY LECITHIN, SALT, BUTTER OIL, MILK, CARRAGEENAN, GUAR GUM, SOYBEAN OIL, BAKING SODA'
 'CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, CORN SYRUP, PECANS, BUTTER (CREAM, SALT), WHEAT FLOUR, EGG YOLKS, SUGAR, DRIED CANE SYRUP, WHISKEY, DRY MALT EXTRACT (BARLEY), SOYBEAN OIL, SALT, EGGS, CARAMEL COLOR, PEANUT OIL, GUAR GUM, BAKING SODA, CARRAGEENAN, SOY LECITHIN. MAY CONTAIN OTHER TREE NUTS'
 'CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, SUGAR, COFFEE EXTRACT, COCONUT OIL, EGG YOLKS, COCOA PROCESSED WITH ALKALI, WHEAT FLOUR, BUTTER (CREAM, SALT), CHOCOLATE LIQUOR, CORN SYRUP, COCOA POWDER, CANOLA OIL, GUAR GUM, SOY LECITHIN, SALT, CARRAGEENAN, NATURAL FLAVOR, MILK FAT, BAKING SODA, VANILLA EXTRACT'
 'CREAM, SKIM MILK, WATER, LIQUID SUGAR (SUGAR, WATER), SUGAR, CORN SYRUP, CANOLA OIL, CREAM CHEESE (PASTEURIZED MILK, CREAM, CHEESE CULTURES, SALT, CAROB BEAN GUM), COCONUT OIL, EGG YOLKS, WHEAT FLOUR, DRIED CANE SYRUP, SOYBEAN OIL, GRAHAM FLOUR, EGGS, COCOA (PROCESSED WITH ALKALI), NATURAL FLAVORS, COCOA, GUAR GUM, BUTTEROIL, MILK PROTEIN CONCENTRATE, CORN STARCH, SALT, SOY LECITHIN, TAPIOCA STARCH, PECTIN, CARAMELIZED SUGAR SYRUP, BAKING SODA, MOLASSES, HONEY, CARRAGEENAN, VANILLA EXTRACT'
 'CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, CHERRIES, SUGAR, EGG YOLKS, COCONUT OIL, COCOA (PROCESSED WITH ALKALI), FRUIT AND VEGETABLE CONCENTRATES (COLOR), COCOA POWDER, GUAR GUM, NATURAL FLAVORS, LEMON JUICE CONCENTRATE, CARRAGEENAN, MILK FAT, SOY LECITHIN'
 'CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, SUGAR, COCONUT OIL, EGG YOLKS, BUTTER (CREAM, SALT), COFFEE, WHEAT FLOUR, MILK PROTEIN CONCENTRATE, COCOA (PROCESSED WITH ALKALI), SOYBEAN OIL, GUAR GUM, NATURAL FLAVOR, SALT, CORN STARCH, CANOLA OIL, RUM, SOY LECITHIN, CHOCOLATE, BAKING SODA, CARRAGEENAN'
 'CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, WHEAT FLOUR, SUGAR, BROWN SUGAR, EGG YOLKS, BUTTER (CREAM, SALT), EXPELLER PRESSED SOYBEAN OIL, EGGS, COCONUT OIL, CHOCOLATE LIQUOR, VANILLA EXTRACT, COCOA (PROCESSED WITH ALKALI), COCOA POWDER, SALT, MOLASSES, GUAR GUM, COCOA BUTTER, NATURAL FLAVOR, CARRAGEENAN, MILK FAT, SOY LECITHIN'
 'CREAM, LIQUID SUGAR (SUGAR, WATER), SKIM MILK, WATER, SUGAR, COCOA (PROCESSED WITH ALKALI), WHEAT FLOUR, COCOA POWDER, SOYBEAN OIL, EGG YOLKS, INVERT CANE SUGAR, EGGS, EGG WHITES, GUAR GUM, SALT, CARRAGEENAN, VANILLA EXTRACT, MALTED BARLEY FLOUR, SODIUM BICARBONATE'
 'CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER), WATER, CORN SYRUP, WHEAT FLOUR, POWDERED SUGAR (CANE SUGAR, CORNSTARCH), SUGAR, EGG YOLKS, COCOA (PROCESSED WITH ALKALI), BUTTER (CREAM, SALT), BARLEY MALT, TAPIOCA SYRUP, EGG WHITES, MILK, COCOA, SEA SALT, GUAR GUM, NATURAL FLAVOR, PECTIN, VANILLA EXTRACT, ENZYMES, CARRAGEENAN, SALT, BAKING SODA'
 'CREAM, LIQUID SUGAR (SUGAR, WATER), SKIM MILK, WATER, COCOA (PROCESSED WITH ALKALI), WHEAT FLOUR, SUGAR, SOYBEAN OIL, BROWN SUGAR, EGG YOLKS, CHOCOLATE LIQUOR, COCOA, HONEY, GUAR GUM, COCOA BUTTER, VANILLA EXTRACT, SALT, BAKING SODA, NATURAL FLAVORS, SOY LECITHIN, CARRAGEENAN']

**Reasoning**:
The previous steps have explored the data types, missing values, descriptive statistics, and unique values in object columns. The missing values in 'subhead' and 'description' have been handled. The next step is to create features based on the text data in 'description' and 'ingredients' as outlined in the overall task and previous steps.

In [16]:
products_df['description_length'] = products_df['description'].apply(len)
keywords = ['chocolate', 'vanilla', 'strawberry', 'nuts', 'caramel', 'cookie dough']
products_df['keyword_count'] = 0

for index, row in products_df.iterrows():
    count = sum(keyword.lower() in row['ingredients'].lower() for keyword in keywords)
    products_df.loc[index, 'keyword_count'] = count

display(products_df.head())

,brand,key,name,subhead,description,rating,rating_count,ingredients,description_length,keyword_count
0,bj,0_bj,Salted Caramel Core,Sweet Cream Ice Cream with Blonde Brownies & a...,Find your way to the ultimate ice cream experi...,3.7,208,"CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER),...",227,1
1,bj,1_bj,Netflix & Chilll'd™,Peanut Butter Ice Cream with Sweet & Salty Pre...,There’s something for everyone to watch on Net...,4.0,127,"CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER),...",285,2
2,bj,2_bj,Chip Happens,A Cold Mess of Chocolate Ice Cream with Fudge ...,Sometimes “chip” happens and everything’s a me...,4.7,130,"CREAM, LIQUID SUGAR (SUGAR, WATER), SKIM MILK,...",263,1
3,bj,3_bj,Cannoli,Mascarpone Ice Cream with Fudge-Covered Pastry...,As a Limited Batch that captured the rapture o...,3.6,70,"CREAM, SKIM MILK, LIQUID SUGAR (SUGAR, WATER),...",232,1
4,bj,4_bj,Gimme S’more!™,Toasted Marshmallow Ice Cream with Chocolate C...,It’s a gimme: there’s always room for s’more. ...,4.5,281,"CREAM, SKIM MILK, WATER, LIQUID SUGAR (SUGAR, ...",211,2

## Choose a model

### Subtask:
Select an appropriate machine learning model for regression to predict the ice cream ratings.

## Predict ratings

### Subtask:
Use the trained Random Forest Regressor model to predict ice cream ratings on the test dataset (`X_test`).

**Reasoning**:
Use the trained Random Forest Regressor model to make predictions on the test dataset and store the predictions in `y_pred`.

In [17]:
y_pred = model.predict(X_test)

## Summary:

### Data Analysis Key Findings

*   The dataset contains 8 columns, including 'brand', 'key', 'name', 'subhead', 'description', and 'ingredients' as object types, and 'rating' (float64) and 'rating_count' (int64) as numerical types.
*   Missing values were found in the 'subhead' (184) and 'description' (4) columns and were filled with placeholder strings.
*   The 'brand' column has 4 unique values, while 'key', 'name', and 'ingredients' have a large number of unique values.
*   Two new features, `description_length` and `keyword_count`, were engineered from the textual data.
*   A Random Forest Regressor model was chosen for predicting ice cream ratings.

### Insights or Next Steps

*   Consider techniques for handling the high cardinality of categorical features like 'key', 'name', and 'ingredients' if they are to be used in the model.
*   Evaluate the performance of the chosen model using appropriate regression metrics (e.g., Mean Squared Error, R-squared) and potentially explore other regression models for comparison.